jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      integration tests were successful:
        type: job
        job_key: integration-tests
        states: [passed]

    context:

      tasks:
        ubuntu-2204:
          name: Ubuntu 22.04 (jammy) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2204.yml
          environment_variables:
            DEPLOY_NEW_BORROW: 'true'

        ubuntu-2004:
          name: Ubuntu 20.04 (focal) LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2004.yml
          environment_variables:
            DEPLOY_NEW_BORROW: 'true'

        debian-bullseye:
          name: Debian 11 (bullseye)
          include: cider-ci/task-components/container-deploy/task-debian-11.yml
          environment_variables:
            DEPLOY_NEW_BORROW: 'true'

