jobs:
  test-container-deploy:
    include: cider-ci/task-components/container-deploy.yml

    name: Test Deploy to Container

    run_when:
      integration tests were successful:
        type: job
        job_key: integration-tests
        states: [passed]

    context:
      tasks:
        ubuntu-2004:
          name: Ubuntu 20.04 LTS
          include: cider-ci/task-components/container-deploy/task-ubuntu-2004.yml

        debian-buster:
          name: Debian 10 (buster)
          include: cider-ci/task-components/container-deploy/task-debian-10.yml

        # NOTE: while new borrow is optional, make sure it works
        debian-buster-with-new-borrow:
          name: Debian 10 (buster) [WITH NEW BORROW]
          include: cider-ci/task-components/container-deploy/task-debian-10.yml
          environment_variables:
            DEPLOY_NEW_BORROW: 'true'

        # NOTE: while ruby with jemalloc is optional, make sure it works
        debian-buster-with-jemalloc:
          name: Debian 10 (buster) [WITH JEMALLOC]
          include: cider-ci/task-components/container-deploy/task-debian-10.yml
          environment_variables:
            EXTRA_ANSIBLE_VARS_JSON: '{"ruby_use_jemalloc": true}'

        # FIXME: normal deploy works but not in the container yet
        # debian-bullseye:
        #   name: Debian 11 (bullseye)
        #   include: cider-ci/task-components/container-deploy/task-debian-11.yml
