jobs:
  integration-tests:
    name: Integration Tests

    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
        exclude_match: ^.*(no-ci|hotspot).*$

    context:
      task_defaults:
        max_trials: 3

      include:
        - path: cider-ci/integration-tests/main.yml
